name: rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - pip
  - sphinx-rtd-theme
  - cython
  - numpy<2.0
  - sncosmo=2.10.1
  - astropy
  - matplotlib
  - pandas
  - scipy
  - george
  - sphinx
  - pip:
    - sphinx-tabs
